version: "3.8"
services:
  ratings-app-auth-redis:
    image: redis:7.0.9-alpine
    container_name: ratings-app-auth-redis
    ports:
      - "6379:6379"
  ratings-app-mariadb:
    image: mariadb:10.11.2-jammy
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: root
    ports:
      - "3306:3306"
    volumes:
      - ratings-app-data:/var/lib/mysql
  ratings-app-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: ratings-app-mariadb
      PMA_PORT: 3306
    ports:
      - "8080:80"
volumes:
  ratings-app-data:
networks:
  default:
    name: ratings-app-default